### PR TITLE
Add support LPC54114 & LPC54608 LPCXpresso boards

### PR DESCRIPTION
**Pull request by mmahadevan108**

### CODE REVIEW

**Comment by mmahadevan108** [comment]
cc @c1728p9 @flit @jasonNXP

**Comment by mmahadevan108** [comment]
Hi Russ, is there any additional information required for the PR.

**Comment by c1728p9** [comment]
Hi @mmahadevan108, no additional information is needed on this PR. I'll let you know if that changes.

**Comment by mmahadevan108** [comment]
I have included support for LPC54608 in this branch as well.

**Comment by mmahadevan108** [comment]
@c1728p9 Can this be integrated into the code-base.

**Comment by c1728p9** [comment]
I think the reason global variables were getting overwritten was due to this bug:
https://github.com/mbedmicro/DAPLink/pull/283

**Comment by mmahadevan108** [comment]
Can this be integrated into the code-base.

**Comment by c1728p9** [comment]
Seems good to me. @sg- can you merge?

**Pull request merged**
