### PR TITLE
Adding board support for CC3220sf

### PR DESCRIPTION
**Pull request by dragoniteArm**

### CODE REVIEW

**Comment by flit** [comment]
@dragoniteArm This change set modifies the permissions of every file in the repo, it seems. The PR cannot be merged until this is fixed.

**Comment by linlingao** [comment]
@flit Peter has left. Should we cancel this PR and submit the changes properly in another PR?

**Comment by flit** [comment]
@linlingao Yes, please. This PR also needed major cleanup, since it unnecessarily touched 300 files, and needs to be squashed.

**Comment by linlingao** [comment]
@flit You can abandon this PR now. I've cleaned up the code and resubmitted under PR46.

**Comment by flit** [comment]
Thanks!

**Pull request closed without merging**
