### PR TITLE
[NCS36510] Add support for NCS36510 with dual flash bank (640K) support.

### PR DESCRIPTION
**Pull request by maclobdell**
squashed commits from maclobdell/flashalgo which has contributions from pradeep-gr to enable NCS36510 support with 640K flash support.

### CODE REVIEW

**Comment by maclobdell** [comment]
this needs to be tested

**Comment by maclobdell** [comment]
after initial tests, there appears to be a problem with applications >320K.   @pradeep-gr can you review and check for issues with the proposed changes.  This should match the flash blob that you recently generated, but it does not.  I suspect that there are differences due to the rebase on the master branch, but there still seems to be a problem.

**Comment by pradeep-gr** [comment]
@maclobdell Please mention steps to reproduce the issue?

**Comment by maclobdell** [comment]
@pradeep-gr   Generate uVision project using the instructions at https://github.com/mbedmicro/FlashAlgo/blob/master/README.md.  Then open Keil uVision and compile.  You will get a file in FlashAlgo\projectfiles\uvision\ncs36510\build\ncs36510 called flash_blob.c.  copy that file to the daplink repo at DAPLink\source\target\onsemi\ncs36510.  following a similar method, you generate uVision project file (if you haven't already) using the instructions at https://github.com/mbedmicro/DAPLink/blob/master/docs/DEVELOPERS-GUIDE.md.  Then compile and you'll get a binary image sam3u2c_ncs36510rf_if_crc.bin at DAPLink\projectfiles\uvision\sam3u2c_ncs36510rf_if\build.

**Comment by maclobdell** [comment]
@c1728p9  @sg-  can this be merged?

**Pull request merged**
